# Generated by Django 5.2.3 on 2025-06-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(help_text='WhatsApp or phone number', max_length=100)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
